In [17]:
import pandas as pd

# Have a readable format and then load the file
pd.set_option("display.float_format", "{:,.2f}".format)
df = pd.read_csv("../data/processed/steam_games_analysis.csv")

# Initial data details
df.head()
df.info()
df.isna().sum()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   app_id                     89618 non-null  int64
 1   name                       89618 non-null  str
 2   release_date               89618 non-null  str
 3   price                      89618 non-null  float64
 4   developers                 89618 non-null  str
 5   publishers                 89618 non-null  str
 6   genres                     89618 non-null  str
 7   positive_reviews           89618 non-null  int64
 8   negative_reviews           89618 non-null  int64
 9   review_pct                 53199 non-null  float64
 10  total_reviews              53199 non-null  float64
 11  estimated_owners           89618 non-null  str
 12  average_playtime_forever   89618 non-null  int64
 13  peak_ccu                   89618 non-null  int64
 14  recommendations            89618 non-null  int64
 15  release_year               89618 non-null  int64
 16  price_type                 89618 non-null  str
 17  estimated_owners_midpoint  89618 non-null  float64
 18  success_label              89618 non-null  str
 19  price_bucket               89618 non-null  str
dtypes: float64(4), int64(7), str(9)
memory usage: 13.7 MB

,app_id,price,positive_reviews,negative_reviews,review_pct,total_reviews,average_playtime_forever,peak_ccu,recommendations,release_year,estimated_owners_midpoint
count,"89,618.00","89,618.00","89,618.00","89,618.00","53,199.00","53,199.00","89,618.00","89,618.00","89,618.00","89,618.00","89,618.00"
mean,"1,656,903.96",7.31,"1,269.90",209.80,0.77,"2,216.73",114.91,98.34,"1,009.40","2,020.76","101,133.76"
std,"916,838.98",13.33,"31,814.41","6,114.31",0.18,"45,955.34","6,814.75","5,717.54","22,048.15",3.09,"1,677,279.39"
min,20.00,0.00,0.00,0.00,0.00,10.00,0.00,0.00,0.00,"1,997.00",0.00
25%,"855,052.50",0.99,1.00,0.00,0.67,21.00,0.00,0.00,0.00,"2,018.00","10,000.00"
50%,"1,524,730.00",4.99,10.00,2.00,0.81,55.00,0.00,0.00,0.00,"2,021.00","10,000.00"
75%,"2,430,852.50",9.99,58.00,17.00,0.91,238.00,0.00,0.00,0.00,"2,023.00","10,000.00"
max,"3,542,350.00",999.98,"7,480,813.00","1,135,108.00",1.00,"8,632,939.00","1,462,997.00","1,212,356.00","4,401,572.00","2,025.00","350,000,000.00"

In [18]:
# Checking to make sure there are negative review scores
df.loc[
    df["review_pct"] < 0,
    [
        "name",
        "positive_reviews",
        "negative_reviews",
        "review_pct",
        "total_reviews"
    ]
].head(20)

Empty DataFrame
Columns: [name, positive_reviews, negative_reviews, review_pct, total_reviews]
Index: []

In [19]:
df["review_pct"].min()
df["review_pct"].max()

np.float64(1.0)

In [20]:
# Missing values in each column
df.isna().sum()

# Summary statistics
df.describe()

# Check for duplicate games
df.duplicated().sum()

# Most expensive games
df.sort_values("price", ascending=False).head(10)

# Games with the highest review counts
df.sort_values("total_reviews", ascending=False).head(10)

# Games with the highest estimated owners
df.sort_values("estimated_owners_midpoint", ascending=False).head(10)

,app_id,name,release_date,price,developers,publishers,genres,positive_reviews,negative_reviews,review_pct,total_reviews,estimated_owners,average_playtime_forever,peak_ccu,recommendations,release_year,price_type,estimated_owners_midpoint,success_label,price_bucket
2,570,Dota 2,2013-07-09,0.00,['Valve'],['Valve'],"['Action', 'Strategy', 'Free To Play']",1998462,451338,0.81,"2,452,595.00",200000000 - 500000000,43031,555977,14337,2013,Free,"350,000,000.00",Successful,Free
0,730,Counter-Strike 2,2012-08-21,0.00,['Valve'],['Valve'],"['Action', 'Free To Play']",7480813,1135108,0.86,"8,632,939.00",100000000 - 200000000,33189,1212356,4401572,2012,Free,"150,000,000.00",Successful,Free
60,1063730,New World: Aeternum,2021-09-28,59.99,['Amazon Games'],['Amazon Games'],"['Action', 'Adventure', 'Massively Multiplayer...",196334,89723,0.68,"244,917.00",50000000 - 100000000,8059,10420,244795,2021,Paid,"75,000,000.00",Low / Unknown,$30-$60
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0.00,['PUBG Corporation'],"['KRAFTON, Inc.']","['Action', 'Adventure', 'Massively Multiplayer...",1487960,1024436,0.59,"2,513,842.00",50000000 - 100000000,0,616738,1732007,2017,Free,"75,000,000.00",Low / Unknown,Free
25,304930,Unturned,2017-07-07,0.00,['Smartly Dressed Games'],['Smartly Dressed Games'],"['Action', 'Adventure', 'Casual', 'Indie', 'Fr...",504673,48084,0.91,"552,875.00",50000000 - 100000000,0,13530,7597,2017,Free,"75,000,000.00",Top Performer,Free
3,271590,Grand Theft Auto V Legacy,2015-04-13,0.00,['Rockstar North'],['Rockstar Games'],"['Action', 'Adventure']",1719950,250012,0.87,"1,803,832.00",50000000 - 100000000,19323,117698,1803063,2015,Free,"75,000,000.00",Successful,Free
42,1623730,Palworld,2024-01-18,22.49,['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",350225,21784,0.94,"314,689.00",50000000 - 100000000,0,33835,314601,2024,Paid,"75,000,000.00",Top Performer,$15-$30
34,1938090,Call of Duty®,2022-10-27,0.00,"['Treyarch', 'Raven Software', 'Beenox', 'High...",['Activision'],['Action'],405742,286287,0.55,"379,855.00",50000000 - 100000000,5271,56993,379597,2022,Free,"75,000,000.00",Low / Unknown,Free
82,1599340,Lost Ark,2022-02-11,0.00,['Smilegate RPG'],['Amazon Games'],"['Action', 'Adventure', 'Massively Multiplayer...",143421,58224,0.71,"201,669.00",50000000 - 100000000,6874,21875,65064,2022,Free,"75,000,000.00",Low / Unknown,Free
10,2358720,Black Myth: Wukong,2024-08-19,59.99,['Game Science'],['Game Science'],"['Action', 'Adventure', 'RPG']",1098373,37811,0.96,"825,621.00",50000000 - 100000000,0,35990,825294,2024,Paid,"75,000,000.00",Top Performer,$30-$60